In [88]:
# Loading the needed packages/lib
import pandas as pd
from sklearn.model_selection import train_test_split 
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import LogisticRegression


def selectkbest(indep_X,dep_Y,n): 
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_X,dep_Y) 
        selectk_features = fit1.transform(indep_X) 
        return selectk_features

    
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train) 
        X_test = sc.transform(X_test)
        return X_train, X_test, y_train, y_test
    
def logistic(X_train,y_train,X_test):
    from sklearn.linear_model import LogisticRegression
    classifier = LogisticRegression(random_state = 0)
    classifier.fit(X_train, y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return  classifier,Accuracy,report,X_test,y_test,cm 

    
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
           
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm

def Navie(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm         
    
    
def knn(X_train,y_train,X_test):
           
        # Fitting K-NN to the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      


def random(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
     from sklearn.metrics import confusion_matrix  
     cm = confusion_matrix(y_test, y_pred) 
     from sklearn.metrics import accuracy_score  
     from sklearn.metrics import classification_report 
     Accuracy=accuracy_score(y_test, y_pred )
     report=classification_report(y_test, y_pred)  
     return  classifier,Accuracy,report,X_test,y_test,cm
    
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,index in enumerate(dataframe.index):      
        dataframe['Logistic'][index]=acclog[number]       
        dataframe['SVMl'][index]=accsvml[number]
        dataframe['SVMnl'][index]=accsvmnl[number]
        dataframe['KNN'][index]=accknn[number]
        dataframe['Navie'][index]=accnav[number]
        dataframe['Decision'][index]=accdes[number]
        dataframe['Random'][index]=accrf[number]
    return dataframe # return the function to dataframe

In [89]:
dataset1=pd.read_csv("prep.csv") # reading.loading the csv dataset 

df2=dataset1 # taking a back up of original dataset

df2 = pd.get_dummies(df2, dtype = int, drop_first=True) # remove first redundant col wrt to nominal col

indep_X=df2.drop('classification_yes', axis=1) # dropping 'classification_yes' from indep_x variable
dep_Y=df2['classification_yes'] # calling dep_y 'classification_yes'

In [112]:
# calling SelectKBest func inputting indep_X,dep_Y and no of feature in args from sklearn.feature_selection import SelectKBest    
kbest=selectkbest(indep_X,dep_Y,7)
# created a empty list to append the final value
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [113]:
# from the 6 feature we are split X_train, X_test, y_train, y_test & calling split_scalar and i/p 6 feature and dep_y
X_train, X_test, y_train, y_test=split_scalar(kbest,dep_Y) 
    
#running ML algo  and find out classifier,Accuracy,report,X_test,y_test,cm in algo func input x, y and x_test        
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy) # we can either append classifier or Accuracy or report or X_test or y_test or cm to get score.

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)
# finally calling selectk_Classification and input neccessary args   
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [18]:
# finally print the value in the table   
result #3

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.82  0.82  0.82  0.85   0.8     0.84   0.83

In [22]:
result #4

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.85  0.82  0.83  0.86  0.79     0.89   0.89

In [26]:
result #5

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.94  0.94  0.95  0.89  0.83     0.96   0.95

In [30]:
result #6

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.95  0.96  0.96  0.93  0.89     0.97   0.97

In [35]:
result #7

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.97  0.97  0.97  0.97  0.91     0.98   0.97

In [114]:
result

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.97  0.97  0.97  0.97  0.91     0.98   0.97